(defun scene-sine-stack (&key (downsample-factor *default-downsample-factor*))
    (let* ((factor (normalize-downsample-factor downsample-factor))
           (height 1080)
           (width 1920)
           (render-height (* height factor))
           (render-width (* width factor))
           (image (make-blank-image render-height render-width))
           (layers 180)
           (wave-amplitude 46.0)
           (wave-period 220.0)
           (vertical-shift 1)
           (line-thickness 2)
           (center-r 70.0)
           (center-g 160.0)
           (center-b 255.0)
           (scaled-wave-amplitude (* wave-amplitude factor))
           (scaled-wave-period (* wave-period factor))
           (scaled-vertical-shift (* vertical-shift factor))
           (scaled-line-thickness (max 1 (* line-thickness factor))))
        (dotimes (yy render-height)
            (dotimes (xx render-width)
                (let* ((base (round (* 24 (/ yy (max 1 (- render-height 1))))))
                       (bg-r base)
                       (bg-g (+ 4 base))
                       (bg-b (+ 12 base)))
                    (set-pixel image xx yy bg-r bg-g bg-b))))
        (dotimes (layer layers)
            (let* ((intensity (+ 0.20 (* layer (/ 0.80 (max 1 (- layers 1))))))
                   (layer-center-r (* center-r intensity))
                   (layer-center-g (* center-g intensity))
                   (layer-center-b (* center-b intensity)))
                (dotimes (xx render-width)
                    (let* ((diag-y (round (* (- render-height 1)
                                             (/ xx (max 1 (- render-width 1))))))
                           (phase (* 2.0 pi (/ xx scaled-wave-period)))
                           (wave-y (round (+ diag-y
                                             (* scaled-wave-amplitude (sin phase))
                                             (* layer scaled-vertical-shift)))))
                        (loop for dy from (- scaled-line-thickness) to scaled-line-thickness do
                            (blend-pixel image
                                         xx
                                         (+ wave-y dy)
                                         (round layer-center-r)
                                         (round layer-center-g)
                                         (round layer-center-b)
                                         0.50))))))
        (write-png-file (output-path "sine_stack_1920x1080.png")
                        (downsample-image image factor))
        t))

(register-scene "sine" #'scene-sine-stack
                :description "1920x1080 diagonal sine meta-stack")
(register-scene "sine-stack" #'scene-sine-stack
                :description "Alias for 'sine'")

(defun scene-sine-classic (&key (downsample-factor *default-downsample-factor*))
    (let* ((factor (normalize-downsample-factor downsample-factor))
           (height 1080)
           (width 1920)
           (render-height (* height factor))
           (render-width (* width factor))
           (image (make-blank-image render-height render-width))
           (layers 20)
           (wave-amplitude 46.0)
           (wave-period 220.0)
           (vertical-shift 14)
           (line-thickness 2)
           (center-r 70.0)
           (center-g 160.0)
           (center-b 255.0)
           (scaled-wave-amplitude (* wave-amplitude factor))
           (scaled-wave-period (* wave-period factor))
           (scaled-vertical-shift (* vertical-shift factor))
           (scaled-line-thickness (max 1 (* line-thickness factor))))
        (dotimes (yy render-height)
            (dotimes (xx render-width)
                (let* ((base (round (* 24 (/ yy (max 1 (- render-height 1))))))
                       (bg-r base)
                       (bg-g (+ 4 base))
                       (bg-b (+ 12 base)))
                    (set-pixel image xx yy bg-r bg-g bg-b))))
        (dotimes (layer layers)
            (let* ((intensity (+ 0.20 (* layer (/ 0.80 (max 1 (- layers 1))))))
                   (layer-center-r (* center-r intensity))
                   (layer-center-g (* center-g intensity))
                   (layer-center-b (* center-b intensity)))
                (dotimes (xx render-width)
                    (let* ((diag-y (round (* (- render-height 1)
                                             (/ xx (max 1 (- render-width 1))))))
                           (phase (* 2.0 pi (/ xx scaled-wave-period)))
                           (wave-y (round (+ diag-y
                                             (* scaled-wave-amplitude (sin phase))
                                             (* layer scaled-vertical-shift)))))
                        (loop for dy from (- scaled-line-thickness) to scaled-line-thickness do
                            (blend-pixel image
                                         xx
                                         (+ wave-y dy)
                                         (round layer-center-r)
                                         (round layer-center-g)
                                         (round layer-center-b)
                                         0.50))))))
        (write-png-file (output-path "sine_stack_classic_1920x1080.png")
                        (downsample-image image factor))
        t))

(register-scene "sine-classic" #'scene-sine-classic
                :description "Original wide-gap sine stack")

(defun scene-fullpagesin (&key (downsample-factor *default-downsample-factor*))
    (let* ((factor (normalize-downsample-factor downsample-factor))
           (height 1080)
           (width 1920)
           (render-height (* height factor))
           (render-width (* width factor))
           (image (make-blank-image render-height render-width))
           (wave-amplitude 46.0)
           (wave-period 220.0)
           (vertical-shift 14)
           (line-thickness 2)
           (midline (floor render-height 2))
           (scaled-wave-amplitude (* wave-amplitude factor))
           (scaled-wave-period (* wave-period factor))
           (scaled-vertical-shift (* vertical-shift factor))
           (scaled-line-thickness (max 1 (* line-thickness factor)))
           (layers (max 1
                        (ceiling (/ (+ (- render-height midline)
                                       (* 2 scaled-wave-amplitude)
                                       40.0)
                                    (max 1 scaled-vertical-shift))))))
        (dotimes (yy render-height)
            (dotimes (xx render-width)
                (let* ((base (round (* 24 (/ yy (max 1 (- render-height 1))))))
                       (bg-r base)
                       (bg-g (+ 4 base))
                       (bg-b (+ 12 base)))
                    (set-pixel image xx yy bg-r bg-g bg-b))))
        (dotimes (layer layers)
            (dotimes (xx render-width)
                (let* ((diag-y (round (+ midline
                                         (* (- render-height 1 midline)
                                            (/ xx (max 1 (- render-width 1)))))))
                       (phase (* 2.0 pi (/ xx scaled-wave-period)))
                       (wave-y (round (+ (- diag-y scaled-wave-amplitude)
                                         (* scaled-wave-amplitude (sin phase))
                                         (* layer scaled-vertical-shift)))))
                    (loop for dy from (- scaled-line-thickness) to scaled-line-thickness do
                        (blend-pixel image
                                     xx
                                     (+ wave-y dy)
                                     255
                                     255
                                     255
                                     0.62)))))
        (write-png-file (output-path "fullpagesin_1920x1080.png")
                        (downsample-image image factor))
        t))

(register-scene "fullpagesin" #'scene-fullpagesin
                :description "Classic sine stack extended to fill the whole page")
